# Generated by Django 5.2.8 on 2025-11-23 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(help_text='Título conciso da solicitação de suporte.', max_length=255, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('ATND', 'Em Atendimento'), ('AGRD', 'Aguardando Informação'), ('RESOLV', 'Resolvido'), ('FECH', 'Fechado/Arquivado')], default='NOVO', help_text='Estado atual do tópico no fluxo de trabalho.', max_length=6, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicos_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Admin/Suporte Responsável')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Tópico de Suporte',
                'verbose_name_plural': 'Tópicos de Suporte',
                'ordering': ['status', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(help_text='O texto da comunicação.', verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Envio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_suporte_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='suporte.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['timestamp'],
            },
        ),
    ]
