# Generated by Django 5.2.8 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(help_text='O texto da comunicação.', verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Envio')),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(help_text='Título conciso da solicitação de suporte.', max_length=255, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('ATND', 'Em Atendimento'), ('AGRD', 'Aguardando Informação'), ('RESOLV', 'Resolvido'), ('FECH', 'Fechado/Arquivado')], default='NOVO', help_text='Estado atual do tópico no fluxo de trabalho.', max_length=6, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Tópico de Suporte',
                'verbose_name_plural': 'Tópicos de Suporte',
                'ordering': ['status', '-atualizado_em'],
            },
        ),
    ]
