# Generated by Django 5.2.8 on 2025-11-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsuporte',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_suporte_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='topico',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicos_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Admin/Suporte Responsável'),
        ),
        migrations.AddField(
            model_name='topico',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='mensagemsuporte',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='suporte.topico', verbose_name='Tópico'),
        ),
    ]
