# Generated by Django 5.2.8 on 2025-11-27 00:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('ra_numero', models.CharField(max_length=20, verbose_name='RA (Registro do Aluno) - Número')),
                ('ra_digito_verificador', models.CharField(max_length=2, verbose_name='RA - Dígito Verificador')),
            ],
            options={
                'verbose_name': 'Registro de Aluno',
                'verbose_name_plural': 'Registros de Alunos',
            },
        ),
        migrations.CreateModel(
            name='RegistroColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula_ou_identificador', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula ou Identificador')),
                ('funcao', models.CharField(choices=[('DIRECAO', 'Direção'), ('VICE_DIR', 'Vice Direção'), ('COORD_PED', 'Coordenação Pedagógica'), ('SECRETARIA', 'Secretaria'), ('AGENTE_ESCOLAR', 'Agente de Org./Ser. Escolar (QSE)'), ('PROATI', 'Proati'), ('MERENDA', 'Merenda'), ('LIMPEZA', 'Limpeza'), ('ESTAGIO', 'Estágio'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Função no Colégio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Colaborador Ativo')),
            ],
            options={
                'verbose_name': 'Registro de Colaborador',
                'verbose_name_plural': 'Registros de Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='RegistroOutrosVisitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Vínculo')),
            ],
            options={
                'verbose_name': 'Registro de Outro Visitante',
                'verbose_name_plural': 'Registros de Outros Visitantes',
            },
        ),
        migrations.CreateModel(
            name='RegistroProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('tipo_professor', models.CharField(choices=[('REGENTE', 'Regente'), ('COLABORATIVO', 'Colaborativo'), ('ED_FISICA', 'Ed. Física'), ('ARTES', 'Artes'), ('CULTURA_MOV', 'Cultura do Movimento'), ('TUTOR', 'Tutor'), ('ORIENT_ESTUDOS', 'Orientação de Estudos'), ('TUTORIA', 'Tutoria'), ('INGLES', 'Inglês'), ('SALA_LEITURA', 'Sala de Leitura'), ('PROATI', 'Proati'), ('ESTAGIO', 'Estágio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Professor')),
            ],
            options={
                'verbose_name': 'Registro de Professor',
                'verbose_name_plural': 'Registros de Professores',
            },
        ),
        migrations.CreateModel(
            name='RegistroURE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função ou Cargo na URE')),
            ],
            options={
                'verbose_name': 'Registro URE',
                'verbose_name_plural': 'Registros URE',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('COLABORADOR', 'Colaborador'), ('RESPONSAVEL', 'Responsável'), ('URE', 'URE (Unidade Regional de Ensino)'), ('OUTRO_VISITANTE', 'Outros Visitantes')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário')),
                ('is_fotografo', models.BooleanField(default=False, verbose_name='Pode gerenciar suas próprias galerias')),
                ('is_fotografo_master', models.BooleanField(default=False, verbose_name='Pode gerenciar todas as galerias')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
                ('registro_aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registroaluno', verbose_name='Vínculo de Aluno')),
                ('registro_colaborador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registrocolaborador', verbose_name='Vínculo de Colaborador')),
                ('registro_visitante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registrooutrosvisitantes', verbose_name='Vínculo de Outro Visitante')),
                ('registro_professor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registroprofessor', verbose_name='Vínculo de Professor')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TURMA', 'Turma Escolar (Ex: 3A-2025)'), ('SETOR', 'Setor/Corpo Docente (Ex: Coordenação)'), ('PROJETO', 'Projeto/Adicional (Criação Restrita)')], default='TURMA', max_length=20, verbose_name='Tipo de Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Grupo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Grupo Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('auth_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_ranieri', to='auth.group', verbose_name='Grupo de Autenticação Django')),
            ],
            options={
                'verbose_name': 'Grupo de Audiência',
                'verbose_name_plural': 'Grupos de Audiência',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número WhatsApp')),
                ('outro_contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro Contato (Ex: Telefone Fixo)')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado (UF)')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mini-biografia ou Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado')),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='RegistroResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('alunos', models.ManyToManyField(related_name='responsaveis', to='users.registroaluno', verbose_name='Alunos Dependentes')),
            ],
            options={
                'verbose_name': 'Registro de Responsável',
                'verbose_name_plural': 'Registros de Responsáveis',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='registro_responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registroresponsavel', verbose_name='Vínculo de Responsável'),
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_registro', to='users.grupo', verbose_name='Grupo')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroaluno', verbose_name='Registro Aluno')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registrocolaborador', verbose_name='Registro Colaborador')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registrooutrosvisitantes', verbose_name='Registro Outro Visitante')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroprofessor', verbose_name='Registro Professor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroresponsavel', verbose_name='Registro Responsável')),
                ('ure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroure', verbose_name='Registro URE')),
            ],
            options={
                'verbose_name': 'Membro do Grupo de Audiência',
                'verbose_name_plural': 'Membros do Grupo de Audiência',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='registro_ure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='users.registroure', verbose_name='Vínculo de URE'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Turma (Ex: 3º A)')),
                ('ano_letivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Turma Ativa')),
                ('professor_regente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_regidas', to='users.registroprofessor', verbose_name='Professor Regente')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('nome', 'ano_letivo')},
            },
        ),
        migrations.AddField(
            model_name='registroprofessor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores_adicionais', to='users.turma', verbose_name='Turmas Adicionais'),
        ),
        migrations.AddField(
            model_name='registroaluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='users.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='JSONUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='json_uploads/', verbose_name='Arquivo JSON')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('turma', models.ForeignKey(help_text='Selecione a turma à qual os alunos do arquivo serão associados.', on_delete=django.db.models.deletion.CASCADE, to='users.turma', verbose_name='Turma de Destino')),
            ],
            options={
                'verbose_name': 'Upload de Seeder JSON',
                'verbose_name_plural': 'Upload de Seeders JSON',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registroaluno',
            unique_together={('ra_numero', 'ra_digito_verificador', 'turma')},
        ),
    ]
