# Generated by Django 5.2.8 on 2025-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='json_uploads/', verbose_name='Arquivo JSON')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name': 'Upload de Seeder JSON',
                'verbose_name_plural': 'Upload de Seeders JSON',
            },
        ),
    ]
