# Generated by Django 5.2.8 on 2025-11-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jsonupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonupload',
            name='turma',
            field=models.ForeignKey(default=1, help_text='Selecione a turma à qual os alunos do arquivo serão associados.', on_delete=django.db.models.deletion.CASCADE, to='users.turma', verbose_name='Turma de Destino'),
            preserve_default=False,
        ),
    ]
