# Generated by Django 5.2.8 on 2025-12-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membrogrupo_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrogrupo',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroaluno', verbose_name='Registro Aluno'),
        ),
        migrations.AlterField(
            model_name='membrogrupo',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registrocolaborador', verbose_name='Registro Colaborador'),
        ),
        migrations.AlterField(
            model_name='membrogrupo',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroprofessor', verbose_name='Registro Professor'),
        ),
        migrations.AlterField(
            model_name='membrogrupo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroresponsavel', verbose_name='Registro Responsável'),
        ),
        migrations.AlterField(
            model_name='membrogrupo',
            name='ure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registroure', verbose_name='Registro URE'),
        ),
        migrations.AlterField(
            model_name='membrogrupo',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.registrooutrosvisitantes', verbose_name='Registro Outro Visitante'),
        ),
    ]
