# Generated by Django 5.2.8 on 2025-11-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jsonupload_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registro_aluno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registroaluno', verbose_name='Vínculo de Aluno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registro_colaborador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registrocolaborador', verbose_name='Vínculo de Colaborador'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registro_professor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registroprofessor', verbose_name='Vínculo de Professor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registro_responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registroresponsavel', verbose_name='Vínculo de Responsável'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registro_ure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registroure', verbose_name='Vínculo de URE'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registro_visitante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.registrooutrosvisitantes', verbose_name='Vínculo de Outro Visitante'),
        ),
    ]
