# Generated by Django 5.2.8 on 2025-11-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjSimCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Evento/Receita')),
                ('link_video', models.CharField(help_text='Insira APENAS o ID do vídeo (ex: FjI-N_rA7t0). A URL de embed será gerada automaticamente.', max_length=50, unique=True, verbose_name='ID do Vídeo (YouTube)')),
                ('descricao_detalhada', models.TextField(blank=True, help_text='Conteúdo completo do evento ou os passos detalhados da receita.', verbose_name='Descrição Detalhada/Receita')),
                ('ordem_exibicao', models.IntegerField(help_text='Define a sequência cronológica ou temática. Deve ser um número inteiro único.', unique=True, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Evento Simoninha na Cozinha',
                'verbose_name_plural': 'Eventos Simoninha na Cozinha',
                'ordering': ['ordem_exibicao'],
            },
        ),
    ]
