# Generated by Django 5.2.8 on 2025-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_cozinha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projsimcozinha',
            name='link_externo',
            field=models.URLField(blank=True, help_text='URL completa do vídeo para o botão "Assistir no YouTube" (ex: https://www.youtube.com/watch?v=ID).', null=True, unique=True, verbose_name='Link de Acesso Externo'),
        ),
        migrations.AlterField(
            model_name='projsimcozinha',
            name='link_video',
            field=models.CharField(help_text='Insira APENAS o ID do vídeo (ex: FjI-N_rA7t0). Usado para incorporação (embed).', max_length=50, unique=True, verbose_name='ID do Vídeo (YouTube)'),
        ),
    ]
