# Generated by Django 5.2.8 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloCoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_livro', models.CharField(choices=[('historia', 'História do Coral'), ('repertorio', 'Repertório')], default='historia', max_length=20, verbose_name='Tipo de Livro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Capítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo (Página)')),
                ('ordem_exibicao', models.IntegerField(help_text='Define a sequência lógica de visualização (1, 2, 3...). Deve ser único por Tipo de Livro.', verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Capítulo do Coral',
                'verbose_name_plural': 'Capítulos do Coral',
                'ordering': ['tipo_livro', 'ordem_exibicao'],
                'unique_together': {('tipo_livro', 'ordem_exibicao')},
            },
        ),
    ]
