# Generated by Django 5.2.8 on 2026-01-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Capítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo (Página)')),
                ('ordem_exibicao', models.IntegerField(help_text='Define a sequência lógica (1, 2, 3...)', unique=True, verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capítulo de História',
                'verbose_name_plural': 'Capítulos de História',
                'ordering': ['ordem_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='RepertorioCoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome da Música')),
                ('arquivo', models.FileField(upload_to='coral/repertorio/', verbose_name='Arquivo de Mídia')),
                ('tipo_arquivo', models.CharField(choices=[('pdf', 'Documento PDF'), ('audio', 'Áudio (MP3)'), ('video', 'Vídeo (MP4)')], max_length=10, verbose_name='Tipo do Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Letra')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Música do Repertório',
                'verbose_name_plural': 'Músicas do Repertório',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='CapituloCoral',
        ),
    ]
