# Generated by Django 5.2.8 on 2026-01-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0002_historiacoral_repertoriocoral_delete_capitulocoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoriocoral',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Vídeo (YouTube)'),
        ),
        migrations.AlterField(
            model_name='repertoriocoral',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='coral/repertorio/', verbose_name='Arquivo de Mídia'),
        ),
        migrations.AlterField(
            model_name='repertoriocoral',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('pdf', 'Documento PDF'), ('audio', 'Áudio (MP3)'), ('video', 'Vídeo (MP4)'), ('youtube', 'Link do YouTube')], max_length=10, null=True, verbose_name='Tipo do Conteúdo'),
        ),
    ]
