# Generated by Django 5.2.8 on 2026-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0003_repertoriocoral_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoriocoral',
            name='video_url',
        ),
        migrations.AddField(
            model_name='repertoriocoral',
            name='video_id',
            field=models.CharField(blank=True, help_text='Insira apenas o ID, ex: 9IZYnK4T00Y', max_length=50, null=True, verbose_name='ID do Vídeo (YouTube)'),
        ),
    ]
