# Generated by Django 5.2.8 on 2026-01-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0004_remove_repertoriocoral_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoriocoral',
            name='tipo_arquivo',
        ),
    ]
