# Generated by Django 5.2.8 on 2026-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0005_remove_repertoriocoral_tipo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoriocoral',
            name='nome_exibicao_arquivo',
            field=models.CharField(blank=True, help_text='Ex: Partitura Soprano. Se vazio, exibe o título da música.', max_length=100, null=True, verbose_name='Nome de Exibição do Download'),
        ),
    ]
