# Generated by Django 5.2.8 on 2026-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0006_repertoriocoral_nome_exibicao_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repertoriocoral',
            options={'ordering': ['ordem_exibicao'], 'verbose_name': 'Música do Repertório', 'verbose_name_plural': 'Músicas do Repertório'},
        ),
        migrations.AddField(
            model_name='repertoriocoral',
            name='link_externo',
            field=models.URLField(blank=True, help_text='URL completa do vídeo para o botão "Assistir no YouTube".', null=True, unique=True, verbose_name='Link de Acesso Externo'),
        ),
        migrations.AddField(
            model_name='repertoriocoral',
            name='ordem_exibicao',
            field=models.IntegerField(help_text='Define a sequência do repertório. Deve ser um número inteiro único.', null=True, unique=True, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='repertoriocoral',
            name='video_id',
            field=models.CharField(blank=True, help_text='Insira APENAS o ID (ex: 9IZYnK4T00Y). Usado para incorporação (embed).', max_length=50, null=True, verbose_name='ID do Vídeo (YouTube)'),
        ),
    ]
