# Generated by Django 5.2.8 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Título da Galeria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO', 'Processando'), ('REVISAO', 'Pronta para Revisão'), ('PUBLICADA', 'Publicada'), ('ARQUIVADA', 'Arquivada')], default='RASCUNHO', max_length=20, verbose_name='Status de Publicação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo_original', models.CharField(max_length=255, verbose_name='Nome Original do Arquivo')),
                ('arquivo_original', models.FileField(max_length=500, upload_to='repo/originais/', verbose_name='Arquivo Original')),
                ('arquivo_processado', models.ImageField(blank=True, max_length=500, null=True, upload_to='repo/processadas/', verbose_name='Arquivo Processado')),
                ('status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente de Upload'), ('UPLOADED', 'Upload Concluído'), ('PROCESSANDO', 'Processando'), ('PROCESSADA', 'Processada'), ('ERRO', 'Erro no Processamento')], default='PENDENTE', max_length=20, verbose_name='Status do Processamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do Repositório',
                'verbose_name_plural': 'Imagens do Repositório',
            },
        ),
        migrations.CreateModel(
            name='WatermarkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name="Nome da Marca D'água")),
                ('arquivo_marca_dagua', models.ImageField(upload_to='watermarks/', verbose_name='Arquivo (PNG com Transparência)')),
                ('posicao', models.CharField(choices=[('TL', 'Top-Left'), ('TR', 'Top-Right'), ('BL', 'Bottom-Left'), ('BR', 'Bottom-Right'), ('C', 'Center')], default='BR', max_length=2, verbose_name='Posição')),
                ('opacidade', models.FloatField(default=0.7, help_text='Opacidade de 0.0 (transparente) a 1.0 (sólido).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Configuração de Marca D'água",
                'verbose_name_plural': "Configurações de Marca D'água",
            },
        ),
    ]
