# Generated by Django 5.2.8 on 2025-11-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='fotografo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Fotógrafo'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='grupos_acesso',
            field=models.ManyToManyField(related_name='galerias_acessiveis', to='users.grupo', verbose_name='Grupos com Acesso'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='repositorio.galeria', verbose_name='Galeria'),
        ),
        migrations.AddField(
            model_name='curtida',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='repositorio.imagem', verbose_name='Imagem Curtida'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='watermark_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.watermarkconfig', verbose_name="Marca D'água Padrão"),
        ),
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together={('usuario', 'imagem')},
        ),
    ]
