# Generated by Django 5.2.8 on 2025-11-28 21:56

import config.storages_conf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo_original',
            field=models.FileField(max_length=500, storage=config.storages_conf.PrivateMediaStorage(), upload_to='repo/originais/', verbose_name='Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo_processado',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=config.storages_conf.PublicMediaStorage(), upload_to='repo/processadas/', verbose_name='Arquivo Processado'),
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='arquivo_marca_dagua',
            field=models.ImageField(storage=config.storages_conf.PublicMediaStorage(), upload_to='watermarks/', verbose_name='Arquivo (PNG com Transparência)'),
        ),
    ]
