# Generated by Django 5.2.8 on 2025-11-30 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_imagem_arquivo_original_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='fotografo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Fotógrafo'),
            preserve_default=False,
        ),
    ]
