# Generated by Django 5.2.8 on 2025-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_imagem_fotografo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='status_processamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Upload'), ('UPLOADED', 'Upload Concluído'), ('PROCESSANDO', 'Processando'), ('PROCESSADA', 'Processada'), ('ERRO', 'Erro no Processamento'), ('UPLOAD_PENDENTE', 'Upload Pendente')], default='PENDENTE', max_length=20, verbose_name='Status do Processamento'),
        ),
    ]
