# Generated by Django 5.2.8 on 2025-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_alter_imagem_status_processamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='status_processamento',
            field=models.CharField(choices=[('UPLOAD_PENDENTE', 'Upload Pendente'), ('UPLOADED', 'Upload Concluído'), ('PROCESSANDO', 'Processando'), ('PROCESSADA', 'Processada'), ('ERRO', 'Erro no Processamento')], default='UPLOAD_PENDENTE', max_length=20, verbose_name='Status do Processamento'),
        ),
    ]
