# Generated by Django 5.2.8 on 2025-11-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0006_alter_imagem_status_processamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='status',
            field=models.CharField(choices=[('PR', 'Rascunho'), ('PC', 'Processando'), ('RV', 'Pronta para Revisão'), ('PB', 'Publicada'), ('AR', 'Arquivada')], default='PR', max_length=2, verbose_name='Status de Publicação'),
        ),
    ]
