# Generated by Django 5.2.8 on 2025-12-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0007_galeria_alterado_em_alter_galeria_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galeria_capa', to='repositorio.imagem', verbose_name='Imagem de Capa'),
        ),
    ]
