# Generated by Django 5.2.8 on 2025-12-01 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_galeria_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-data_do_evento', '-criado_em'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerias'},
        ),
        migrations.AddField(
            model_name='galeria',
            name='data_do_evento',
            field=models.DateField(default=datetime.date.today, help_text='A data em que o evento fotografado realmente ocorreu.', verbose_name='Data do Evento'),
        ),
    ]
