# Generated by Django 5.2.8 on 2025-12-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0009_alter_galeria_options_galeria_data_do_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='acesso_publico',
            field=models.BooleanField(default=False, help_text='Se marcado, a galeria é visível para qualquer usuário, mesmo que não esteja logado.', verbose_name='Acesso Público'),
        ),
    ]
