# Generated by Django 5.2.8 on 2025-12-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0010_galeria_acesso_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='repositorio.galeria', verbose_name='Galeria'),
        ),
    ]
