# Generated by Django 5.2.8 on 2025-12-17 01:43

import config.storages_conf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0012_alter_imagem_arquivo_processado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermarkconfig',
            name='arquivo_marca_dagua',
            field=models.ImageField(storage=config.storages_conf.PrivateMediaStorage(), upload_to='watermarks/', verbose_name='Arquivo (PNG com Transparência)'),
        ),
    ]
