# Generated by Django 5.2.8 on 2025-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0013_alter_watermarkconfig_arquivo_marca_dagua'),
        ('users', '0002_alter_membrogrupo_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='grupos_acesso',
            field=models.ManyToManyField(blank=True, related_name='galerias_acessiveis', to='users.grupo', verbose_name='Grupos com Acesso'),
        ),
    ]
