# Generated by Django 5.2.8 on 2026-01-15 12:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0014_alter_galeria_grupos_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=storages.backends.s3.S3Storage(), upload_to='repo/thumbs/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo_original',
            field=models.FileField(max_length=500, storage=storages.backends.s3.S3Storage(), upload_to='repo/originais/', verbose_name='Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo_processado',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=storages.backends.s3.S3Storage(), upload_to='repo/processadas/', verbose_name='Arquivo Processado'),
        ),
        migrations.AlterField(
            model_name='watermarkconfig',
            name='arquivo_marca_dagua',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='watermarks/', verbose_name='Arquivo (PNG com Transparência)'),
        ),
    ]
