# Generated by Django 5.2.8 on 2026-01-15 17:44

import config.storages_conf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0015_galeria_slug_imagem_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo_processado',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=config.storages_conf.PrivateMediaStorage(), upload_to='repo/processadas/', verbose_name='Arquivo Processado'),
        ),
    ]
