# Generated by Django 5.2.8 on 2025-11-21 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_customuser_registro_aluno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Amigável do Canal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Canal Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Canal')),
                ('grupo', models.OneToOneField(help_text='Apenas membros deste Grupo têm acesso ao Canal.', on_delete=django.db.models.deletion.CASCADE, related_name='canal_chat', to='users.grupo', verbose_name='Grupo de Audiência Vinculado')),
            ],
            options={
                'verbose_name': 'Canal de Mensagens',
                'verbose_name_plural': 'Canais de Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora de Envio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='mensagens.canal', verbose_name='Canal')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['timestamp'],
            },
        ),
    ]
