# Generated by Django 5.2.8 on 2025-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Amigável do Canal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Canal Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text='Identificador único para URLs.', max_length=100, unique=True, verbose_name='Slug do Canal')),
            ],
            options={
                'verbose_name': 'Canal de Mensagens',
                'verbose_name_plural': 'Canais de Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora de Envio')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='UltimaLeituraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(auto_now=True, verbose_name='Data da Última Leitura')),
            ],
            options={
                'verbose_name': 'Última Leitura do Usuário',
                'verbose_name_plural': 'Últimas Leituras dos Usuários',
            },
        ),
    ]
