# Generated by Django 5.2.8 on 2025-11-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_envio'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='timestamp',
            new_name='data_envio',
        ),
    ]
