# Generated by Django 5.2.8 on 2025-11-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensagens', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Canal'),
        ),
        migrations.AddField(
            model_name='canal',
            name='grupo',
            field=models.OneToOneField(help_text='Apenas membros deste Grupo têm acesso ao Canal.', on_delete=django.db.models.deletion.CASCADE, related_name='canal_chat', to='users.grupo', verbose_name='Grupo de Audiência Vinculado'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='mensagens.canal', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='ultimaleiturausuario',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_usuarios', to='mensagens.canal', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='ultimaleiturausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimas_leituras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='ultimaleiturausuario',
            unique_together={('usuario', 'canal')},
        ),
    ]
