# Generated by Django 5.2.8 on 2025-11-22 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_alter_mensagem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='slug',
            field=models.SlugField(default='slug-padrao', help_text='Identificador único para URLs.', max_length=100, unique=True, verbose_name='Slug do Canal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UltimaLeituraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(auto_now=True, verbose_name='Data da Última Leitura')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_usuarios', to='mensagens.canal', verbose_name='Canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimas_leituras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Última Leitura do Usuário',
                'verbose_name_plural': 'Últimas Leituras dos Usuários',
                'unique_together': {('usuario', 'canal')},
            },
        ),
    ]
