# Generated by Django 5.2.8 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Capítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Página/Capítulo')),
                ('ordem_exibicao', models.IntegerField(help_text='Número único que define a sequência deste capítulo no livro (1, 2, 3, etc.).', unique=True, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Capítulo Histórico',
                'verbose_name_plural': 'Capítulos Históricos',
                'ordering': ['ordem_exibicao'],
            },
        ),
    ]
