"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import environ # Importação necessária para gerenciar variáveis de ambiente

# ==============================================================================
# 1. SETUP BÁSICO E VARIÁVEIS DE AMBIENTE
# ==============================================================================

# Constrói caminhos dentro do projeto como: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializa o django-environ
env = environ.Env(
    # Define valores padrão (fallback) para o tipo e valor da variável
    DEBUG=(bool, False)
)

# Lendo o arquivo .env (se existir)
environ.Env.read_env(BASE_DIR / '.env')

# Segurança
# Recomendação: Sempre defina SECRET_KEY no arquivo .env
SECRET_KEY = env('SECRET_KEY', default='django-insecure-#e=9pnvz)s2kda5nf=8r05jk+q6+%kyh*)s+46*&c1)(o35s8h')

# Modo DEBUG
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# ==============================================================================
# 2. DEFINIÇÃO DE APLICATIVOS (Apenas os built-in por enquanto)
# ==============================================================================

INSTALLED_APPS = [
    # meus app
    'users',
    # outros
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # config
    'formtools',
    'core',
    #meus app (continua)
    'historia',
    'coral',
    'sim_cozinha',
    'brinc_dialogando',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Adiciona diretório global de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
# ASGI_APPLICATION será adicionado mais tarde, após a configuração do Channels


# ==============================================================================
# 3. BANCO DE DADOS (Configurado para PostgreSQL via environ)
# ==============================================================================

DATABASES = {
    # Lê a URL de conexão da variável de ambiente DATABASE_URL.
    # O driver 'psycopg2-binary' está instalado para suportar PostgreSQL.
    # Exemplo Prod: 'postgres://user:password@host:port/dbname'
    # Fallback Dev: 'sqlite:///db.sqlite3'
    'default': env.db_url(
        'DATABASE_URL',
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3')
    )
}


# ==============================================================================
# 4. VALIDAÇÃO DE SENHA
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ==============================================================================
# 5. INTERNACIONALIZAÇÃO (PT-BR)
# ==============================================================================

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo' # Fuso horário brasileiro

USE_I18N = True # Habilita a internacionalização

USE_TZ = True # Habilita suporte a fuso horário (Timezone support)


# ==============================================================================
# 6. ARQUIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'

# Diretório para arquivos estáticos globais (além dos de cada app)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configuração para coletar todos os arquivos estáticos em um local para deploy
STATIC_ROOT = BASE_DIR / "staticfiles"


# ==============================================================================
# 7. CHAVE PRIMÁRIA PADRÃO
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# 8. CONFIGURAÇÕES DE AUTENTICAÇÃO (Adicionado)
# ==============================================================================

# Define o modelo de usuário customizado a ser usado pelo Django
AUTH_USER_MODEL = 'users.CustomUser'

# Define a URL para onde redirecionar após o login
LOGIN_REDIRECT_URL = 'users:dashboard' # Redireciona para a Dashboard após o login

# Define a URL para onde redirecionar após o logout
LOGOUT_REDIRECT_URL = 'users:login' # Redireciona para a página de login após o logout

# Define a URL usada pelo sistema de autenticação para o login
LOGIN_URL = 'users:login' # Garante que o Django saiba qual é a URL de login


# ==============================================================================
# 9. CONFIGURAÇÕES DE SESSÃO
# ==============================================================================

SESSION_SAVE_EVERY_REQUEST = True